# site settings
title: Workman
subtitle: Nicholas
email: filler
description: Artifical Intelligence Developer, <br />Computational Linguist, <br />& jiujiteiro.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Nicholas Workman
street_address: 1234 Yeet Ln
city: Los Angeles
state: CA
zip_code: 55555
country: United States of America
phone: (720) 340-1561
year: 2020
formspree_endpoint: https://formspree.io/f/xjvppypn

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: https://500px.com/p/momosimo
facebook_url:
github_url: https://github.com/Momosimo
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/nicktwerkman/
linkedin_url: https://www.linkedin.com/in/nicholasworkman/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/nicktwerkman

# build settings
markdown: kramdown

sass:
  style: compressed
